apiVersion: apps/v1
kind: Deployment
metadata:
  name: v2raysub
spec:
  selector:
    matchLabels:
      name: v2raysub
  template:
    metadata:
      labels:
        name: v2raysub
    spec:
      hostNetwork: true
      containers:
        - name: v2ray
          image: docker.io/v2fly/v2fly-core:v5.2.1
          workingDir: /v2ray-client/v2ray
          command: ["./v2raysub"]
          volumeMounts:
            - mountPath: /v2ray-client
              name: v2ray-client
      volumes:
        - name: v2ray-client
          hostPath:
            path: /root/v2ray-client
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: v2raysub
spec:
  ports:
    - name: tcp
      port: 80
      protocol: TCP
      targetPort: 18088
  selector:
    name: v2raysub
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    traefik.ingress.kubernetes.io/preserve-host: "true"
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
    traefik.ingress.kubernetes.io/redirect-regex: ^https://www.(.*)
    traefik.ingress.kubernetes.io/redirect-replacement: https://$1
  name: v2raysub
spec:
  rules:
    - host: www.lqingcloud.cn
      http:
        paths:
          - backend:
              service:
                name: v2raysub
                port:
                  name: tcp
            path: /v2ray/
            pathType: Prefix
    - host: lqingcloud.cn
      http:
        paths:
          - backend:
              service:
                name: v2raysub
                port:
                  name: tcp
            path: /v2ray/
            pathType: Prefix
  tls:
    - hosts:
        - lqingcloud.cn
      secretName: lqingcloud.cn
